export const USER_REQUEST = 'USER_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_CHATS = ' USER_CHATS';
export const USER_CHATS_SUCCESS = ' USER_CHATS_SUCCESS';

export const CHATS_NEW_CHAT = 'NEW_CHAT';
export const CHATS_NEW_CHAT_SUCCESS = 'CHATS_NEW_CHAT_SUCCESS';
export const CHATS_GET = 'CHATS_GET';
export const CHATS_GET_SUCCESS = 'CHATS_GET_SUCCESS';

export const CHAT_CONNECT = 'CHAT_CONNECT';
export const CHAT_CONNECT_SUCCESS = 'CHAT_CONNECT_SUCCESS';
export const CHAT_NEW_MESSAGE = 'CHAT_NEW_MESSAGE';
export const CHAT_NEW_MESSAGE_SUCCESS = 'CHAT_NEW_MESSAGE_SUCCESS';
export const CHAT_GET_MEMBERS = 'CHAT_GET_MEMBERS';
export const CHAT_GET_MEMBERS_SUCCESS = 'CHAT_GET_MEMBERS_SUCCESS';

export const SUBSCRIBE = 'SUBSCRIBE';
